/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Day {
    date: Time;
    activities: Array<Activity>;
}
export interface Activity {
    id: bigint;
    title: string;
    time: string;
    notes: string;
    location: string;
}
export type Time = bigint;
export interface Itinerary {
    id: bigint;
    destination: string;
    tripName: string;
    endDate: Time;
    days: Array<Day>;
    description: string;
    startDate: Time;
}
export interface Proposal {
    id: bigint;
    preferredStartDate: Time;
    destination: string;
    submittedAt: Time;
    email: string;
    preferredEndDate: Time;
    notes: string;
    requesterName: string;
}
export interface backendInterface {
    addActivity(itineraryId: bigint, dayIndex: bigint, title: string, time: string, location: string, notes: string): Promise<void>;
    createItinerary(tripName: string, destination: string, startDate: Time, endDate: Time, description: string): Promise<bigint>;
    deleteActivity(itineraryId: bigint, dayIndex: bigint, activityId: bigint): Promise<void>;
    deleteItinerary(id: bigint): Promise<void>;
    deleteProposal(id: bigint): Promise<void>;
    getAllItineraries(): Promise<Array<Itinerary>>;
    getAllProposals(): Promise<Array<Proposal>>;
    getItineraryById(id: bigint): Promise<Itinerary>;
    submitProposal(requesterName: string, email: string, destination: string, preferredStartDate: Time, preferredEndDate: Time, notes: string): Promise<bigint>;
    updateActivity(itineraryId: bigint, dayIndex: bigint, activityId: bigint, title: string, time: string, location: string, notes: string): Promise<void>;
    updateItinerary(id: bigint, tripName: string, destination: string, startDate: Time, endDate: Time, description: string): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addActivity(arg0: bigint, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addActivity(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addActivity(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createItinerary(arg0: string, arg1: string, arg2: Time, arg3: Time, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createItinerary(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createItinerary(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deleteActivity(arg0: bigint, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteActivity(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteActivity(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteItinerary(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteItinerary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteItinerary(arg0);
            return result;
        }
    }
    async deleteProposal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProposal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProposal(arg0);
            return result;
        }
    }
    async getAllItineraries(): Promise<Array<Itinerary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllItineraries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllItineraries();
            return result;
        }
    }
    async getAllProposals(): Promise<Array<Proposal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProposals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProposals();
            return result;
        }
    }
    async getItineraryById(arg0: bigint): Promise<Itinerary> {
        if (this.processError) {
            try {
                const result = await this.actor.getItineraryById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItineraryById(arg0);
            return result;
        }
    }
    async submitProposal(arg0: string, arg1: string, arg2: string, arg3: Time, arg4: Time, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProposal(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProposal(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateActivity(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateActivity(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateActivity(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateItinerary(arg0: bigint, arg1: string, arg2: string, arg3: Time, arg4: Time, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItinerary(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItinerary(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
