/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Activity = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'time' : IDL.Text,
  'notes' : IDL.Text,
  'location' : IDL.Text,
});
export const Day = IDL.Record({
  'date' : Time,
  'activities' : IDL.Vec(Activity),
});
export const Itinerary = IDL.Record({
  'id' : IDL.Nat,
  'destination' : IDL.Text,
  'tripName' : IDL.Text,
  'endDate' : Time,
  'days' : IDL.Vec(Day),
  'description' : IDL.Text,
  'startDate' : Time,
});
export const Proposal = IDL.Record({
  'id' : IDL.Nat,
  'preferredStartDate' : Time,
  'destination' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'preferredEndDate' : Time,
  'notes' : IDL.Text,
  'requesterName' : IDL.Text,
});

export const idlService = IDL.Service({
  'addActivity' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createItinerary' : IDL.Func(
      [IDL.Text, IDL.Text, Time, Time, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteActivity' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'deleteItinerary' : IDL.Func([IDL.Nat], [], []),
  'deleteProposal' : IDL.Func([IDL.Nat], [], []),
  'getAllItineraries' : IDL.Func([], [IDL.Vec(Itinerary)], ['query']),
  'getAllProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
  'getItineraryById' : IDL.Func([IDL.Nat], [Itinerary], ['query']),
  'submitProposal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Time, Time, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateActivity' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateItinerary' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Time, Time, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Activity = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'time' : IDL.Text,
    'notes' : IDL.Text,
    'location' : IDL.Text,
  });
  const Day = IDL.Record({ 'date' : Time, 'activities' : IDL.Vec(Activity) });
  const Itinerary = IDL.Record({
    'id' : IDL.Nat,
    'destination' : IDL.Text,
    'tripName' : IDL.Text,
    'endDate' : Time,
    'days' : IDL.Vec(Day),
    'description' : IDL.Text,
    'startDate' : Time,
  });
  const Proposal = IDL.Record({
    'id' : IDL.Nat,
    'preferredStartDate' : Time,
    'destination' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'preferredEndDate' : Time,
    'notes' : IDL.Text,
    'requesterName' : IDL.Text,
  });
  
  return IDL.Service({
    'addActivity' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createItinerary' : IDL.Func(
        [IDL.Text, IDL.Text, Time, Time, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteActivity' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'deleteItinerary' : IDL.Func([IDL.Nat], [], []),
    'deleteProposal' : IDL.Func([IDL.Nat], [], []),
    'getAllItineraries' : IDL.Func([], [IDL.Vec(Itinerary)], ['query']),
    'getAllProposals' : IDL.Func([], [IDL.Vec(Proposal)], ['query']),
    'getItineraryById' : IDL.Func([IDL.Nat], [Itinerary], ['query']),
    'submitProposal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Time, Time, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateActivity' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateItinerary' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Time, Time, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };