/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : bigint,
  'title' : string,
  'time' : string,
  'notes' : string,
  'location' : string,
}
export interface Day { 'date' : Time, 'activities' : Array<Activity> }
export interface Itinerary {
  'id' : bigint,
  'destination' : string,
  'tripName' : string,
  'endDate' : Time,
  'days' : Array<Day>,
  'description' : string,
  'startDate' : Time,
}
export interface Proposal {
  'id' : bigint,
  'preferredStartDate' : Time,
  'destination' : string,
  'submittedAt' : Time,
  'email' : string,
  'preferredEndDate' : Time,
  'notes' : string,
  'requesterName' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addActivity' : ActorMethod<
    [bigint, bigint, string, string, string, string],
    undefined
  >,
  'createItinerary' : ActorMethod<[string, string, Time, Time, string], bigint>,
  'deleteActivity' : ActorMethod<[bigint, bigint, bigint], undefined>,
  'deleteItinerary' : ActorMethod<[bigint], undefined>,
  'deleteProposal' : ActorMethod<[bigint], undefined>,
  'getAllItineraries' : ActorMethod<[], Array<Itinerary>>,
  'getAllProposals' : ActorMethod<[], Array<Proposal>>,
  'getItineraryById' : ActorMethod<[bigint], Itinerary>,
  'submitProposal' : ActorMethod<
    [string, string, string, Time, Time, string],
    bigint
  >,
  'updateActivity' : ActorMethod<
    [bigint, bigint, bigint, string, string, string, string],
    undefined
  >,
  'updateItinerary' : ActorMethod<
    [bigint, string, string, Time, Time, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];